backend:
  name: github
  repo: Yash-Singh1/yashsingh.us-v2
  branch: netlifycms
  base_url: 'https://yashsingh-us-v2-git-netlifycms-yash-singh1.vercel.app/'
  auth_endpoint: 'api/auth'

media_folder: public/img/uploads
collections:
  - name: 'home'
    label: 'Home'
    files:
      - label: 'Home page'
        name: 'home'
        file: 'content/home/Home.json'
        preview_path: '/'
        fields:
          - label: Description
            name: description
            widget: string
          - label: Projects
            name: projects
            widget: list
          - label: Skills
            name: skills
            widget: list
            fields:
              - label: Name
                name: name
                widget: string
              - label: Status
                name: status
                widget: string
                hint: proficient
              - label: Icon
                name: icon
                widget: image
              - label: Link
                name: link
                widget: string
              - label: Circlize
                name: circlize
                widget: boolean
                default: false
                required: false
