name: Lint pull requests or commits
on:
  push:
    branches:
      - main
      - development
  pull_request:
    branches:
      - main
      - development
    types:
      - opened
      - synchronize
      - ready_for_review
jobs:
  test:
    name: Lint code
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - uses: pnpm/action-setup@v2.1.0
        with:
          version: 6.32.9

      - name: Install pnpm dependencies
        run: pnpm install

      - name: Lint code
        run: pnpm run lint
