# https://github.com/dependabot/dependabot-core/issues/1736
name: Netlify CMS Format
on:
  pull_request_target:
    types: [assigned, opened, synchronize, reopened, labeled, edited]
permissions: read-all
jobs:
  format-code:
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.pull_request.labels.*.name, 'netlify-cms/draft') || contains(github.event.pull_request.labels.*.name, 'netlify-cms/pending_review') || contains(github.event.pull_request.labels.*.name, 'netlify-cms/pending_publish') }}
    permissions:
      pull-requests: write
      contents: write
    steps:
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Setup PNPM
        uses: pnpm/action-setup@v3.0.0
        with:
          version: 8
      - name: Clone Repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Install Dependencies
        run: pnpm install
      - name: Format Code
        run: pnpm run lint:fix
      - name: Push Changes
        run: |
          git config --global user.name github-actions[bot]
          git config --global user.email github-actions[bot]@users.noreply.github.com
          git add -A
          if ! git diff-index --quiet HEAD; then
            git commit -m "chore: code-style"
            git push
          fi
