# https://github.com/dependabot/dependabot-core/issues/1736
name: Netlify CMS Format
on: pull_request_target
permissions: read-all
jobs:
  format-code:
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.pull_request.labels.*.name, 'netlify-cms/draft') }}
    permissions:
      pull-requests: write
      contents: write
    steps:
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Setup PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 7
      - name: Clone Repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Install Dependencies
        run: pnpm install
      - name: Format Code
        run: pnpm run lint:fix
      - run: |
          git config --global user.name github-actions[bot]
          git config --global user.email github-actions[bot]@users.noreply.github.com
          git add .
          git commit -m "chore: code-style"
          git push
